# Generated by Django 5.2.7 on 2025-11-10 01:24

from django.db import migrations

def crear_grupos_iniciales(apps, schema_editor):
    """
    Crea los grupos de usuarios iniciales (Administrador, Estudiante)
    en la base de datos.
    """
    Group = apps.get_model('auth', 'Group')
    
    # Lista de nombres de grupos a crear
    nombres_grupos = ['Administrador', 'Estudiante']
    
    for nombre in nombres_grupos:
        # get_or_create para evitar errores si el grupo ya existe
        Group.objects.get_or_create(name=nombre)


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_rol_options'),
    ]

    operations = [
        migrations.RunPython(crear_grupos_iniciales),
    ]
