# Generated by Django 5.2.7 on 2025-11-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_crear_grupos_iniciales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
