# Generated by Django 5.2.7 on 2025-11-19 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_rol_delete_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nivel_formacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.nivelformacion'),
        ),
    ]
