# Generated by Django 5.2.7 on 2025-11-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_perfil_nivel_formacion'),
        ('usuarios', '0006_remove_ultima_actividad_racha'),
    ]

    operations = [
    ]
