# Generated by Django 5.2.7 on 2025-11-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_poblar_niveles_formacion'),
        ('usuarios', '0007_merge_20251128_1920'),
    ]

    operations = [
    ]
