# Generated by Django 5.2.7 on 2025-11-29 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preguntas', '0008_merge_20251129_1454'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('puntaje_total', models.IntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
                ('total_preguntas', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_diagnosticas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prueba Diagnóstica',
                'verbose_name_plural': 'Pruebas Diagnósticas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.IntegerField(default=0)),
                ('tiempo_segundos', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('opcion_elegida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.pregunta')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='diagnosticos.pruebadiagnostica')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('prueba', 'pregunta')},
            },
        ),
    ]
