# Generated by Django 5.2.7 on 2025-12-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0001_initial'),
        ('preguntas', '0008_merge_20251129_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestadiagnostica',
            name='preguntas',
            field=models.ManyToManyField(related_name='pruebas_diagnosticas', to='preguntas.pregunta'),
        ),
    ]
