# Generated by Django 5.2.7 on 2025-10-08 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preguntas', '0001_initial'),
        ('simulacros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intentosimulacro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='intento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='simulacros.intentosimulacro'),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='opcion_elegida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.opcion'),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.pregunta'),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='preguntas',
            field=models.ManyToManyField(to='preguntas.pregunta'),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='tipo_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preguntas.tipoexamen'),
        ),
        migrations.AddField(
            model_name='intentosimulacro',
            name='simulacro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacros.simulacro'),
        ),
    ]
