# Generated by Django 5.2.7 on 2025-11-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='tipo_examen',
        ),
        migrations.AddField(
            model_name='componente',
            name='tipo_examen',
            field=models.ManyToManyField(to='preguntas.tipoexamen'),
        ),
        migrations.AddField(
            model_name='tema',
            name='tema_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtemas', to='preguntas.tema'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preguntas.grupo'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas_img/'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preguntas.tema'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
