# Generated by Django 5.2.7 on 2025-11-08 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_remove_pregunta_tipo_examen_componente_tipo_examen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='tema_padre',
        ),
        migrations.AddField(
            model_name='componente',
            name='prioridad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='tipos_examen',
            field=models.ManyToManyField(blank=True, related_name='temas', to='preguntas.tipoexamen'),
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(help_text='Contenido explicativo detallado.')),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('padre_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='preguntas.contenido')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='preguntas.tema')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='contenido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preguntas.contenido'),
        ),
    ]
