# Generated by Django 5.2.7 on 2025-11-10 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_remove_pregunta_tema_remove_tema_tema_padre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='tipos_examen',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.tipoexamen'),
        ),
        migrations.RemoveField(
            model_name='componente',
            name='tipo_examen',
        ),
        migrations.CreateModel(
            name='Temario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.componente')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.tema')),
            ],
        ),
        migrations.AddField(
            model_name='componente',
            name='tipo_examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.tipoexamen'),
        ),
    ]
