# Generated by Django 5.2.7 on 2025-11-11 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_remove_tema_tipos_examen_pregunta_tipo_examen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['prioridad', 'nombre'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AlterModelOptions(
            name='temario',
            options={'verbose_name': 'Temario', 'verbose_name_plural': 'Temarios'},
        ),
        migrations.RemoveField(
            model_name='tema',
            name='componente',
        ),
        migrations.AlterField(
            model_name='temario',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temarios', to='preguntas.componente'),
        ),
        migrations.AlterField(
            model_name='temario',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temarios', to='preguntas.tema'),
        ),
        migrations.AlterUniqueTogether(
            name='temario',
            unique_together={('tema', 'componente')},
        ),
    ]
