# Generated by Django 5.2.7 on 2025-11-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_alter_tema_options_alter_temario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['titulo'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='tipopregunta',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Pregunta', 'verbose_name_plural': 'Tipos de Pregunta'},
        ),
    ]
