# Generated by Django 5.2.7 on 2025-11-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_alter_tema_options_alter_temario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='prioridad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
