# Generated by Django 5.2.7 on 2025-11-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0006_pregunta_prioridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['titulo'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='tipopregunta',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Pregunta', 'verbose_name_plural': 'Tipos de Pregunta'},
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='prioridad',
        ),
    ]
