# Generated by Django 5.2.7 on 2025-11-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0006_alter_grupo_options_alter_tipopregunta_options'),
        ('preguntas', '0007_alter_grupo_options_alter_tipopregunta_options_and_more'),
    ]

    operations = [
    ]
