# Generated by Django 5.2.7 on 2025-12-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0008_merge_20251129_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='explicacion',
            field=models.TextField(blank=True, help_text='Explicación pedagógica que verá el estudiante antes de responder las preguntas.', null=True),
        ),
    ]
