# Generated by Django 5.2.7 on 2025-12-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0009_contenido_explicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa del componente', null=True, upload_to='componentes_img/'),
        ),
    ]
