# Generated by Django 5.2.7 on 2025-11-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_alter_tema_options_alter_temario_options_and_more'),
        ('rutas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='componentes',
            field=models.ManyToManyField(to='preguntas.componente'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='examenes',
            field=models.ManyToManyField(to='preguntas.tipoexamen'),
        ),
    ]
