# Generated by Django 5.2.7 on 2025-11-25 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_alter_tema_options_alter_temario_options_and_more'),
        ('rutas', '0003_ruta_componentes_ruta_examenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='contenido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.contenido'),
        ),
    ]
