# Generated by Django 5.2.7 on 2025-11-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_leccion_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='numero',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
