# Generated by Django 5.2.7 on 2025-12-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0005_leccion_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('aprobada', 'Aprobada'), ('saltada', 'Saltada')], default='vigente', max_length=20),
        ),
    ]
