# Generated by Django 5.2.7 on 2025-12-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0006_leccion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('aprobada', 'Aprobada'), ('saltada', 'Saltada'), ('bloqueada', 'Bloqueada')], default='bloqueada', max_length=20),
        ),
    ]
